name: PHPUnit

on: [push]

env:
  WP_TESTS_DIR: /github/home/wp-tests/wordpress-tests-lib
  WP_CORE_DIR: /github/home/wp-tests/wordpress

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.4 ]
        wordpress-version: [ latest ]
    container:
      image: junaidbhura/wp-tests:php-${{ matrix.php-version }}
    services:
      mysql:
        image: mysql:5.7.27
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Composer dependencies
        run: |
          composer install --no-dev
          composer global require "phpunit/phpunit=5.7.27"
          composer global require "yoast/phpunit-polyfills=1.0.3"

      - name: Install WordPress test suite
        run: bash bin/install-wp-tests.sh wordpress_test root root mysql ${{ matrix.wordpress-version }}

      - name: Tests
        run: | 
          $HOME/.composer/vendor/bin/phpunit --config=phpunit.xml
          WP_MULTISITE=1 $HOME/.composer/vendor/bin/phpunit --config=phpunit.xml
