name: WP Plugin Check
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - trunk

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          coverage: none
          tools: wp-cli

      - name: Install latest version of dist-archive-command
        run: wp package install wp-cli/dist-archive-command:@stable

      - name: Build plugin
        run: |
          wp dist-archive . ./wp-approve-user.zip
          mkdir tmp-build
          unzip wp-approve-user.zip -d tmp-build

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1.0.6
        with:
          build-dir: './tmp-build/wp-approve-user'
