name: WP Plugin Check
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - trunk

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read and format directories and files from .distignore
        id: format_exclusions
        run: |
          # Extract directories (lines starting with '/'), remove empty lines, comments, and leading slashes
          directories=$(grep -v '^#' .distignore | grep '^/' | sed '/^$/d' | sed 's|^/||' | tr -s '\n' ',' | sed 's/,$//')

          # Extract files (lines NOT starting with '/'), remove empty lines and comments
          files=$(grep -v '^#' .distignore | grep -v '^/' | sed '/^$/d' | tr -s '\n' ',' | sed 's/,$//')

          # Save the directories and files to environment variables
          echo "formatted_dirs=$directories" >> $GITHUB_ENV
          echo "formatted_files=$files" >> $GITHUB_ENV

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1.0.6
        with:
          exclude-directories: ${{ env.formatted_dirs }}
          exclude-files: ${{ env.formatted_files }}
