name: PHPCS check
on:
  push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: PHPCS check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: WPCS check
        uses: 10up/wpcs-action@stable
        with:
          standard: 'WordPress'
          enable_warnings: true
          repo_branch: trunk
          extra_args: '--report-json=./phpcs.json'

      - name: Update summary
        run: |
          npm i -g github:10up/phpcs-json-to-md
          phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
          cat phpcs.md >> $GITHUB_STEP_SUMMARY
        if: always()
